communityserver:
  image: onlyoffice/communityserver
  links:
   - documentserver:document_server
   - mailserver:mail_server
  ports:
   - "8081:80"
  stdin_open: true
  tty: true
documentserver:
  image: onlyoffice/documentserver
  stdin_open: true
  tty: true
mailserver:
  image: onlyoffice/mailserver
  hostname: yourdomain.com
  privileged: true
  ports:
   - "25:25"
   - "143:143"
   - "587:587"
  stdin_open: true
  tty: true
